//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysioAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyDiary
    {
        public int Participant_ID { get; set; }
        public System.DateTime Fortnightly_Start_Date { get; set; }
        public System.DateTime Daily_Diary_Date { get; set; }
        public Nullable<byte> FallCount { get; set; }
        public Nullable<byte> SeriousFallCount { get; set; }
    }
}
