//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysioAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degradation
    {
        public int Participant_ID { get; set; }
        public System.DateTime Start_Date { get; set; }
        public int Record_ID { get; set; }
        public string Problem { get; set; }
        public string Severity { get; set; }
        public Nullable<int> Duration { get; set; }
    }
}
