//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysioAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FortnightlyDiary
    {
        public int Participant_ID { get; set; }
        public System.DateTime DiaryStart { get; set; }
        public Nullable<short> FallCount { get; set; }
        public Nullable<short> SeriousFallCount { get; set; }
        public Nullable<short> NurseVisitCount { get; set; }
        public Nullable<short> GPVisitCount { get; set; }
        public Nullable<short> SpecDocVisitCount { get; set; }
        public Nullable<short> EmergencyDeptCount { get; set; }
        public Nullable<short> DaysHospitalized { get; set; }
        public Nullable<short> Grounded_10___30 { get; set; }
        public Nullable<short> Grounded_30___60 { get; set; }
        public Nullable<short> Grounded__60 { get; set; }
        public Nullable<short> HelpFamily { get; set; }
        public Nullable<short> HelpFriendNeighbour { get; set; }
        public Nullable<short> HelpHealthProfessional { get; set; }
        public string DiaryID { get; set; }
        public string SpecDocSeen { get; set; }
        public Nullable<int> OtherCount { get; set; }
        public string OtherSeen { get; set; }
        public Nullable<short> HelpOther { get; set; }
    }
}
