//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysioAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Injury
    {
        public int Participant_ID { get; set; }
        public System.DateTime Fortnightly_Start_Date { get; set; }
        public string Body_Part { get; set; }
        public Nullable<byte> Bruises { get; set; }
        public Nullable<byte> Cuts_Scrapes { get; set; }
        public Nullable<byte> Sprain_Strain { get; set; }
        public Nullable<byte> Dislocation { get; set; }
        public Nullable<byte> Broken_Bone { get; set; }
        public string Comments { get; set; }
    }
}
