//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysioAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programme
    {
        public int Programme_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Capacity { get; set; }
        public int Manager_ID { get; set; }
    }
}
